development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:391f10605c7d3ae80c869fd1b4901431@barb.redistogo.com:10164/
  channel_prefix: IssyoGaro_production
